### PR TITLE
Additional verbs

### PR DESCRIPTION
**Pull request by mccarrom**
Added a lot more verbs both for general movement and specialized sequences around the house. The sequence with the Eagle is now implemented, in a rough draft form. The player can now slide down or jump down the fireplace and the laundry chute. Default behavior for all verbs has been specified.

### CODE REVIEW

**Comment by ewk** [comment]
I am getting a build error on this branch:

```
% go run .
# github.com/ewk/adventure
./parser.go:299:6: syntax error: unexpected capInput, expecting (

```

**Review by ewk — CHANGES_REQUESTED** [review]
This is always the default action if a command entered by the user is not valid: 
```

} else {
				fmt.Println("Not a valid command:", action)
			}
```

What we need to be checking here is if an object was passed to the verb "enter", like we do with other functions.

**Review by ewk — CHANGES_REQUESTED** [review]
There is application code mixed into the parser logic for the cases "use", "taunt", and "slide". It would help keep things organized to move the application logic into separate functions here.

**Review by mccarrom — COMMENTED** [review]
I made the necessary changes

**Comment by ewk** [comment]
Very nice!

**Pull request merged**
