### PR TITLE
Fix #59 Player cannot climb on imaginary items

### LINKED ISSUE #59: If player uses the wrong name for something they want to climb, tell them item not found instead of you can't climb on that.

### PR DESCRIPTION
**Pull request by ewk**
And clean up some linebreaks while we're here ...

### CODE REVIEW

**Review by BethMyre — CHANGES_REQUESTED** [review]
There need to be two separate statements telling a player they can't climb on something.  The first is if they're trying to climb on something they're not allowed to.  ("You can't climb on that!") The second is if they're trying to climb on something not found. ("x not found.")

The reason we don't want everything to default to "you can't climb on that" is that the player won't realize if they misspell something or use the wrong name.  They'll just think they can't climb on it.

Check out how cutStuff handles this for an example.

**Comment by ewk** [comment]
We can't implement that without some fundamental design changes. Room items have isFeature, and we can check if an item exists in a room. But we don't have a designation for what the player is allowed to climb on.  

So in fact, it would be better to drop this PR and retain the generic message when the if/else branches fall through the specific room checks:

```
func climbStuff(feature string) {
	if curRoom.Name == "Basement Lab" && feature == "desk" {
        <---8
	} else if curRoom.Name == "Dining Room" && feature == "dining room table" {
		fmt.Println("From on top of the dining room table you can get a better look at the candelabra.")
		curRoom.Items["candle"].Discovered = true
		fmt.Println("There's wax everywhere but it looks like there might still be a bit of candle left. Is that a candle? Look closer")
	} else {
		fmt.Println("You can't climb on that!")
	}
}
```

**Comment by BethMyre** [comment]
I implemented the change suggested above.

**Review by mccarrom — COMMENTED** [review]
Looks good, and solves the problem of printing two messages.

**Pull request merged**
